# 交叉编译工具链配置：arm-none-eabi-gcc + Ninja

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}gcc)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE   ${TOOLCHAIN_PREFIX}size)

# 避免在配置阶段尝试运行目标平台程序
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

